formatter: "" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  # Azure ExpressRoute gateway module

  This module simplifies the creation of Azure ExpressRoute gateway and (optional) one or more ExpressRoute Circuits (connections). It is designed to be flexible, modular, and easy to use, ensuring a seamless Azure ExpressRoute gateway deployment.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ## Example(s)

  ### Azure ExpressRoute gateway with default options and 1 ExpressRoute Circuit (connection)

  ```hcl
  {{ include ".examples/example_expressroute_gateway.tf"}}
  ```

   ### Azure ExpressRoute gateway with default options, 1 ExpressRoute circuit (connection) and user (point-to-site) VPN

  ```hcl
  {{ include ".examples/example_expressroute_gateway_with_user_vpn.tf"}}
  ```

  # Known issues and limitations

  No known issues or limitations.

  # Author

  Stefan Vonk (vonk.stefan@live.nl) Technical Specialist

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true